# app which returns a status encoded in that path of the url
# /300 -> returns status code 300
# /404 -> returns status code 404
#
# sub path works as well
#
# /prefix/500 -> returns status code 500
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: statusapp
  name: statusapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statusapp
  template:
    metadata:
      labels:
        app: statusapp
    spec:
      containers:
      - image: alpine
        env:
        name: statusapp
        command:
          - sh
          - -c
          - |
            cat<<\EOF>/tmp/websphere
            #!/bin/sh
            read req
            status_code=$(echo "$req"|grep -o '[1-5][0-9][0-9]')

            echo -e "HTTP/1.1 ${status_code} \nContent-Length: 20\n\nstatus code was ${status_code}"
            EOF
            chmod +x /tmp/websphere

            exec nc -lk -s 0.0.0.0 -p 80 -e "/tmp/websphere"
        ports:
          - name: web
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: statusapp
  name: statusapp
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  selector:
    app: statusapp
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: statusapp
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /statusapp
        pathType: Prefix
        backend:
          service:
            name: statusapp
            port:
              number: 80

